# Generated by Django 5.2.17 on 2026-09-24 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("2W", "2-Wheeler"), ("4W", "4-Wheeler")], max_length=2
                    ),
                ),
                ("level", models.IntegerField(default=0)),
                ("is_blocked", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ParkingTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_number", models.CharField(max_length=20, unique=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("2W", "2-Wheeler"), ("4W", "4-Wheeler")], max_length=2
                    ),
                ),
                ("entry_time", models.DateTimeField()),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("stay_minutes", models.IntegerField(blank=True, null=True)),
                ("amount", models.IntegerField(default=0)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[("CASH", "Cash"), ("UPI", "UPI")],
                        max_length=4,
                        null=True,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PARKED", "Parked"), ("PAID", "Paid")],
                        default="PARKED",
                        max_length=6,
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="parking.slot"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parking.vehicle",
                    ),
                ),
            ],
        ),
    ]
